import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Anchor, Box, Button, Grommet, Menu, Page, PageContent, PageHeader } from 'grommet'
import { theme } from '@/src/utils'
import { AppBar } from '@/src/components/AppBar'
import { More } from 'grommet-icons'
import { ProfileScroller } from '@/src/components/ProfileScroller'
import Router from 'next/router'


export default function Home() {
  return (
    <>
      <Head>
        <title>Dog Search App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grommet full theme={theme}>
        <AppBar />
        <Page background='bg1' fill='vertical'>
          <PageContent justify='center'>
            <PageHeader
              title="Dog Identifier"
              subtitle={`Grommet helps you build responsive and accessible mobile-first projects for the web with an easy to use component 
              library.`}
              actions={
              <Box direction="row" gap="small" align="center">
                <Button primary label="Identify a dog" onClick={() => Router.push('/search/')}/>
                <Button label="Upload a profile" onClick={() => Router.push('/upload/new')}/>
              </Box>
              }
              parent={<Anchor label="Home" />}
            />

            </PageContent>
          </Page>

        </Grommet>
      </main>
    </>
  )
};


