import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Anchor, Box, Button, Grommet, Menu, Page, PageContent, PageHeader } from 'grommet'
import { theme } from '@/src/utils'
import { AppBar } from '@/src/components/AppBar'
import { More } from 'grommet-icons'

const actions = [
  {
    label: 'Get Started',
    primary: true,
  },
  {
    label: 'Follow',
    secondary: true,
  },
  {
    label: 'File Issue',
    secondary: true,
  },
] 
const controls = {
  small: (
    <Menu
      dropAlign={{ top: 'bottom', right: 'right' }}
      items={actions.map((action) => ({ label: action.label }))}
      icon={<More />}
    />
  ),
  medium: (
    <>
      <Button {...actions[0]} />
      <Menu
        dropAlign={{ top: 'bottom', right: 'right' }}
        items={actions.slice(1)}
        icon={<More />}
      />
    </>
  ),
  large: actions.map((action) => <Button {...action} />),
} 


export default function Home() {
  return (
    <>
      <Head>
        <title>Dog Search App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grommet full theme={theme}>
        <AppBar />
        <Page>
          <PageContent justify='center'>
            <PageHeader
              title="Dog Seach App"
              subtitle={`Grommet helps you build responsive and accessible mobile-first projects for the web with an easy to use component 
              library.`}
              actions={
              <Box direction="row" gap="small" align="center">
              {controls['large']}
              </Box>
              }
              parent={<Anchor label="Home Page" />}
            />
            </PageContent>
          </Page>

        </Grommet>
      </main>
    </>
  )
}

